### Initialization
no Initialization required

### Scalar and Tensor

#### Creation

In [1]:
% dim= 2
a = [12.3]
ndims(a)
numel(a)
size(a)


a =

   12.3000


ans =

     2


ans =

     1


ans =

     1     1




In [2]:
% dim = 2
aa = [1 2 3;4 5 6; 7 8 9]
ndims(aa)
numel(aa)
size(aa)


aa =

     1     2     3
     4     5     6
     7     8     9


ans =

     2


ans =

     9


ans =

     3     3




In [11]:
1:10
1:3:10
10:-3:1


ans =

     1     2     3     4     5     6     7     8     9    10


ans =

     1     4     7    10


ans =

    10     7     4     1




In [85]:
linspace(1,3,4)


ans =

    1.0000    1.6667    2.3333    3.0000




In [57]:
% dim=3
aaa = rand(3,3,3)
ndims(aaa)
numel(aaa)
size(aaa)


aaa(:,:,1) =

    0.5472    0.2575    0.8143
    0.1386    0.8407    0.2435
    0.1493    0.2543    0.9293


aaa(:,:,2) =

    0.3500    0.6160    0.8308
    0.1966    0.4733    0.5853
    0.2511    0.3517    0.5497


aaa(:,:,3) =

    0.9172    0.7537    0.0759
    0.2858    0.3804    0.0540
    0.7572    0.5678    0.5308


ans =

     3


ans =

    27


ans =

     3     3     3




In [25]:
bb = zeros(3,3)
cc = ones(3,3)
dd = eye(3,3)
ee = rand(3,3)
ff = randn(3,3)

size(ff)
length(ff)

size(ff,1)


bb =

     0     0     0
     0     0     0
     0     0     0


cc =

     1     1     1
     1     1     1
     1     1     1


dd =

     1     0     0
     0     1     0
     0     0     1


ee =

    0.4984    0.5853    0.2551
    0.9597    0.2238    0.5060
    0.3404    0.7513    0.6991


ff =

    1.1006   -1.4916    2.3505
    1.5442   -0.7423   -0.6156
    0.0859   -1.0616    0.7481


gg =

     3


ans =

     3     3


ans =

     3


ans =

     3




#### Round off

In [6]:
a = [1.2, 2.6];
round(a)
ceil(a)
floor(a)


ans =

     1     3


ans =

     2     3


ans =

     1     2


ans =

     1     2




#### Concatention

In [24]:
a=[1:3]
aa=[a;a;a]

bb = [1:3;4:6;7:9]


a =

     1     2     3


aa =

     1     2     3
     1     2     3
     1     2     3


bb =

     1     2     3
     4     5     6
     7     8     9




### Slice and dice
* matlab use () in python, normally use []
* For 2 dims matrix matlab and numpy are simiar, but matlab from 1, numpy from 0
* For 3 dims matrix matlab is different from numpy

In [27]:
ff = [1:3;4:6;7:9]
ff(3)
ff(3,1)
ff(3,3)=1


ff =

     1     2     3
     4     5     6
     7     8     9


ans =

     7


ans =

     7


ff =

     1     2     3
     4     5     6
     7     8     1




In [29]:
ff
ff(1,:)
ff(:,1)
ff(2:end,2:end)
ff(2:end,2:end)=10


ff =

     1     2     3
     4     5     6
     7     8     1


ans =

     1     2     3


ans =

     1
     4
     7


ans =

     5     6
     8     1


ff =

     1     2     3
     4    10    10
     7    10    10




In [18]:
ff
ff==10
find(ff==10)
[row,col]=find(ff==10)
ff(ff==10)
ff(ff<10)
ff(find(ff<10))


ff =

     1     2     3
     4    10    10
     7    10    10


ans =

  3x3 logical array

   0   0   0
   0   1   1
   0   1   1


ans =

     5
     6
     8
     9


row =

     2
     3
     2
     3


col =

     2
     2
     3
     3


ans =

    10
    10
    10
    10


ans =

     1
     4
     7
     2
     3


ans =

     1
     4
     7
     2
     3




In [79]:
xxx=[1:27]
xxx=reshape(xxx,[3,3,3])


xxx =

     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16    17    18    19    20    21    22    23    24    25    26    27


xxx(:,:,1) =

     1     4     7
     2     5     8
     3     6     9


xxx(:,:,2) =

    10    13    16
    11    14    17
    12    15    18


xxx(:,:,3) =

    19    22    25
    20    23    26
    21    24    27




In [84]:
xxx(1,1,:)


ans(:,:,1) =

     1


ans(:,:,2) =

    10


ans(:,:,3) =

    19




In [80]:
xxx(1,:,:)


ans(:,:,1) =

     1     4     7


ans(:,:,2) =

    10    13    16


ans(:,:,3) =

    19    22    25




In [81]:
xxx(:,1,:)


ans(:,:,1) =

     1
     2
     3


ans(:,:,2) =

    10
    11
    12


ans(:,:,3) =

    19
    20
    21




In [82]:
xxx(:,:,1)


ans =

     1     4     7
     2     5     8
     3     6     9




### Operations


In [2]:
a = [1 2; 3 4]
b = [5 6; 7 8]
a.*b
a * b

a^2
a.^2



a =

     1     2
     3     4


b =

     5     6
     7     8


ans =

     5    12
    21    32


ans =

    19    22
    43    50


ans =

     7    10
    15    22


ans =

     1     4
     9    16




In [21]:
[a,b]
[a;b]


ans =

     1     2     5     6
     3     4     7     8


ans =

     1     2
     3     4
     5     6
     7     8




In [1]:
c = [1,2,3;4,5,6]
d = c'


c =

     1     2     3
     4     5     6


d =

     1     4
     2     5
     3     6




In [2]:
% ean along the axis to eliminate that axis
mean(c)
mean(c,'all')
mean(c,1)
mean(c,2)


ans =

    2.5000    3.5000    4.5000


ans =

    3.5000


ans =

    2.5000    3.5000    4.5000


ans =

     2
     5




In [93]:
c = 1
d = 0

c&&d
c||d


c =

     1


d =

     0


ans =

  logical

   0


ans =

  logical

   1




In [10]:
5==5
5<3
2==4
2~=4


ans =

  logical

   1


ans =

  logical

   0


ans =

  logical

   0


ans =

  logical

   1




#### If-Else and Loop

In [99]:
a = 6;
if a==4
    fprintf('a = 4\n')
elseif a==5
    fprintf('a = 5\n')
else
    fprintf('a != 4 or 5')
end

a != 4 or 5


In [102]:
for i=1:3
    fprintf('%i\n',i)
end

1
2
3

