### Initialization

In [1]:
import numpy as np
from scipy import io, integrate, linalg, signal
from scipy.sparse.linalg import eigs

### Scalar and Tensor

#### Creation

In [2]:
# dim = 0
a = np.array(12.3)
print(a.ndim)
print(a.size)
print(a.shape)

0
1
()


In [3]:
# dim = 1
a = np.array([12.3])
print(a.ndim)
print(a.size)
print(a.shape)

1
1
(1,)


In [4]:
# dim = 2
aa = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(aa)
print(aa.ndim)
print(aa.size)
print(aa.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
9
(3, 3)


In [15]:
print(np.arange(1,11))
print(np.arange(1,11,3))
print(np.arange(10,0,-3))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  7 10]
[10  7  4  1]


In [44]:
a = np.random.rand(3,3)
print(a)

print(a[1,2])
print(a[1][2])

[[0.93905792 0.06518302 0.22031389]
 [0.53200729 0.0404185  0.79032899]
 [0.069327   0.42411222 0.39632424]]
0.7903289923551416
0.7903289923551416


In [116]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [5]:
# dim=3
aaa = np.random.rand(3,3,3)
print(aaa)
print(aaa.ndim)
print(aaa.size)
print(aaa.shape)

[[[0.13896147 0.73071462 0.92778573]
  [0.21489156 0.20297691 0.32441293]
  [0.9894482  0.55849008 0.48525878]]

 [[0.44495944 0.10582475 0.73139261]
  [0.47075247 0.04662209 0.92018954]
  [0.65626017 0.97571283 0.8082114 ]]

 [[0.93888836 0.60246946 0.59431899]
  [0.1214641  0.74977279 0.82956858]
  [0.09943451 0.977709   0.52522371]]]
3
27
(3, 3, 3)


In [38]:
bb = np.zeros((3,3))
cc = np.ones((3,3))
dd = np.eye(3)
ee = np.random.rand(3,3)
ff = np.random.randn(3,3)

print(bb,'\n','\n',cc,'\n','\n',dd,'\n','\n',ee,'\n','\n',ff)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 
 [[0.8311934  0.09295303 0.35682259]
 [0.92934338 0.52913129 0.49694809]
 [0.21985509 0.08361343 0.2928492 ]] 
 
 [[-0.57048133  1.17876483  1.43911268]
 [ 0.29674343  1.95041386 -0.59139023]
 [-1.04293995  0.71040104 -0.14563049]]


#### Round off
>Note: the outputs are floats

In [6]:
a = np.array([1.2,2.6])
# outputs are floats
print(np.around(a)) 
print(np.ceil(a))
print(np.floor(a))


[1. 3.]
[2. 3.]
[1. 2.]


#### Concatention

In [26]:
a = np.arange(1,4)
aa = np.vstack((a,a))
print(aa)
np.concatenate
bb = np.vstack((np.arange(1,4),np.arange(4,7),np.arange(7,10)))
print(bb)

[[1 2 3]
 [1 2 3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Slice and dice
* matlab use () in python, normally use []
* For 2 dims matrix matlab and numpy are simiar, but matlab from 1, numpy from 0
* For 3 dims matrix matlab is different from numpy

In [45]:
ff=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ff)
print(ff[2])
print(ff[:,0])
print(ff[2,0])
print(ff[2][0])
ff[2,2]=1
print(ff)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
[1 4 7]
7
7
[[1 2 3]
 [4 5 6]
 [7 8 1]]


In [23]:
print(ff)
print(ff[0,:])
print(ff[:,0])
print(ff[1:,1:])
ff[1:,1:]=10
print(ff)

[[1 2 3]
 [4 5 6]
 [7 8 1]]
[1 2 3]
[1 4 7]
[[5 6]
 [8 1]]
[[ 1  2  3]
 [ 4 10 10]
 [ 7 10 10]]


In [28]:
print(ff)
print(ff==10)
print(np.nonzero(ff==10))
ff[ff<10]

[[ 1  2  3]
 [ 4 10 10]
 [ 7 10 10]]
[[False False False]
 [False  True  True]
 [False  True  True]]
(array([1, 1, 2, 2], dtype=int64), array([1, 2, 1, 2], dtype=int64))


array([1, 2, 3, 4, 7])

In [8]:
xxx = np.arange(1,28).reshape(3,3,3)
print(xxx)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [9]:
xxx[0,0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print(xxx[0,:,:])
print(xxx[:,0,:])
print(xxx[:,:,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 11 12]
 [19 20 21]]
[[ 1  4  7]
 [10 13 16]
 [19 22 25]]


### Operations

In [13]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print('a=\n', a,'\n b= \n', b)
print(a*b)
print(a@b)
print(a**2)
print(a@a)

a=
 [[1 2]
 [3 4]] 
 b= 
 [[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [31]:
print(np.concatenate((a,b),1))
print(np.concatenate((a,b),0))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
d = c.T
print(d)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [9]:
# mean along the axis to eliminate that axis
print(np.mean(c))
print(np.mean(c,0))
print(np.mean(c,1))

3.5
[2.5 3.5 4.5]
[2. 5.]


In [124]:
c = True
d = False
print(c and d)
print(c or d)

False
True


In [12]:
print(5==5)
print(5<3)
print(2==4)
print(2!=4)

True
False
False
True


#### If-else and Loop

In [129]:
a = 6
if a ==4:
    print('a = 4')
elif a==5:
    print('a = 5')
else:
    print('a != 4 or 5')

a != 4 or 5


In [131]:
for i in range(1,4):
    print(i)

1
2
3
